### ISSUE TITLE
Can't send commands

### ISSUE THREAD

**Issue by gcormier** [JoaoLopesF/RemoteDebugger#2]
Telnet'ing to the host, when I type a command and hit ENTER, I just see ^M in the terminal.

Using MobaXterm if that helps.

**Comment by JoaoLopesF** [comment]
Hi, @gcormier, please informe the system operational (MacOS, linux, Windows) and which telnet client that you is using? 

The code in RemoteDebug accept Newline(NL) and Carriage return (CR)
It shows that your client not sending this chars

**Comment by gcormier** [comment]
MobaXTerm on Windows.

**Comment by JoaoLopesF** [comment]
You tried the putty ?
I just yesterday, have some testes with it (I use the native of MacOS daily).

**Comment by gcormier** [comment]
Okay, I'll look into the settings of the telnet client further.

**Comment by JoaoLopesF** [comment]
Ok,
I tried again with putty, and is ok!
I just installing MobaXTerm to see it too.

**Comment by JoaoLopesF** [comment]
I not see any setting to correct this,
but press control-enter, the command is ok
Please notify me if you find the solution
Regards
